### PR TITLE
workspace creation

### PR DESCRIPTION
**Pull request by nithyatsu**
# Description

rad workspace create

## Issue reference

Fixes: #3495

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Adds necessary unit tests for change
* [ ] Adds necessary E2E tests for change
* [ ] Unit tests passing
* [ ] Extended the documentation / Created issue for it

### CODE REVIEW

**Review by asilverman — CHANGES_REQUESTED** [review]
I think the result of this should also print the usage. Also its unclear what are the arguments that it expects, the documentation doesn't list them as required

```bash
rad workspace create
Error: accepts between 1 and 2 arg(s), received 0
```

**Review by AaronCrawfis — CHANGES_REQUESTED** [review]
Small wording updates

**Review by AaronCrawfis — CHANGES_REQUESTED** [review]
Getting an error when trying to follow the example:

```bash
aacrawfi@Aarons-MBP rad % ./rad workspace create kubernetes myworkspace 
Error: accepts between 1 and 1 arg(s), received 2
```

**Review by AaronCrawfis — APPROVED** [review]
Small docs nit, but looks great!

**Review by asilverman — APPROVED** [review]
LGTM!

**Pull request merged**
