### PR TITLE
Create Radius release automation

### PR DESCRIPTION
**Pull request by willdavsmith**
# Description

* Adding a `release.yaml` GitHub workflow for Radius release automation
* Updating release instructions to use the GitHub workflow during the release
* Reformatting release instructions for clarity

## Issue reference

Fixes: radius-project/radius#5659

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Adds necessary unit tests for change
* [ ] Adds necessary E2E tests for change
* [ ] Unit tests passing
* [ ] Extended the documentation / Created issue for it

### Summary
📝🛠️🚀

This pull request enhances the documentation and the script for Radius releases. It improves the `docs/contributing/contributing-releases/README.md` file with more clarity and accuracy, and adds a license header to the `.github/scripts/release.sh` file.

> _We are the masters of the code, we make the rules_
> _We add the license header, we protect our tools_
> _We improve the guide, we share our wisdom and our skills_
> _We update the version, we unleash the Radius thrills_

### Walkthrough
*  Add license header to release script file ([link](https://github.com/project-radius/radius/pull/5766/files?diff=unified&w=0#diff-9904059830ff336439145c31c780f1f2c512b6df04bd983855c52db6f7c6c4deR1-R85))
*  Revise contributing guide for creating and publishing Radius releases ([link](https://github.com/project-radius/radius/pull/5766/files?diff=unified&w=0#diff-4b032acb8e706dca3cf78512aadf53ee8b05354e51cd46023ed550c0625b33fbL3-R9), [link](https://github.com/project-radius/radius/pull/5766/files?diff=unified&w=0#diff-4b032acb8e706dca3cf78512aadf53ee8b05354e51cd46023ed550c0625b33fbL24-R96), [link](https://github.com/project-radius/radius/pull/5766/files?diff=unified&w=0#diff-4b032acb8e706dca3cf78512aadf53ee8b05354e51cd46023ed550c0625b33fbL165-R132), [link](https://github.com/project-radius/radius/pull/5766/files?diff=unified&w=0#diff-4b032acb8e706dca3cf78512aadf53ee8b05354e51cd46023ed550c0625b33fbL228-R138), [link](https://github.com/project-radius/radius/pull/5766/files?diff=unified&w=0#diff-4b032acb8e706dca3cf78512aadf53ee8b05354e51cd46023ed550c0625b33fbR145), [link](https://github.com/project-radius/radius/pull/5766/files?diff=unified&w=0#diff-4b032acb8e706dca3cf78512aadf53ee8b05354e51cd46023ed550c0625b33fbL240-R170))
   *  Remove under construction notice and reference to private resources ([link](https://github.com/project-radius/radius/pull/5766/files?diff=unified&w=0#diff-4b032acb8e706dca3cf78512aadf53ee8b05354e51cd46023ed550c0625b33fbL3-R9))
   *  Simplify prerequisites section ([link](https://github.com/project-radius/radius/pull/5766/files?diff=unified&w=0#diff-4b032acb8e706dca3cf78512aadf53ee8b05354e51cd46023ed550c0625b33fbL3-R9))
   *  Replace manual steps for each repository with a single script invocation ([link](https://github.com/project-radius/radius/pull/5766/files?diff=unified&w=0#diff-4b032acb8e706dca3cf78512aadf53ee8b05354e51cd46023ed550c0625b33fbL24-R96))
   *  Add release verification section ([link](https://github.com/project-radius/radius/pull/5766/files?diff=unified&w=0#diff-4b032acb8e706dca3cf78512aadf53ee8b05354e51cd46023ed550c0625b33fbL24-R96))
   *  Remove redundant post release check section ([link](https://github.com/project-radius/radius/pull/5766/files?diff=unified&w=0#diff-4b032acb8e706dca3cf78512aadf53ee8b05354e51cd46023ed550c0625b33fbL165-R132))
   *  Add sample validation section ([link](https://github.com/project-radius/radius/pull/5766/files?diff=unified&w=0#diff-4b032acb8e706dca3cf78512aadf53ee8b05354e51cd46023ed550c0625b33fbL165-R132))
   *  Fix typo in version number ([link](https://github.com/project-radius/radius/pull/5766/files?diff=unified&w=0#diff-4b032acb8e706dca3cf78512aadf53ee8b05354e51cd46023ed550c0625b33fbL228-R138))
   *  Add blank line for formatting consistency ([link](https://github.com/project-radius/radius/pull/5766/files?diff=unified&w=0#diff-4b032acb8e706dca3cf78512aadf53ee8b05354e51cd46023ed550c0625b33fbR145))
   *  Fix numbering and tag name in patching section ([link](https://github.com/project-radius/radius/pull/5766/files?diff=unified&w=0#diff-4b032acb8e706dca3cf78512aadf53ee8b05354e51cd46023ed550c0625b33fbL240-R170))

### CODE REVIEW

**Review by AaronCrawfis — CHANGES_REQUESTED** [review]

**Review by youngbupark — COMMENTED** [review]
please add comment in yaml. other than this LGTM. I will approve once you add comment.

**Review by youngbupark — APPROVED** [review]
LGTM 👍

**Review by AaronCrawfis — APPROVED** [review]
Looks ok from my end, very cool!

**Review by youngbupark — APPROVED** [review]
@willdavsmith please address the comments from @ytimocin and me before merging this.

**Review by youngbupark — COMMENTED** [review]
This should be last :)

**Review by youngbupark — APPROVED** [review]
looks great to me :) 

Let's cut the first release with workflow! Thanks for getting this done.

**Pull request merged**
