### PR TITLE
Fix issue with rad install

### LINKED ISSUE #6597: Failed to install rad-bicep Failed to install Radius CLI (Error code 403)
### Steps to reproduce (required)
Run install script for MacOS (Silicon) `curl -fsSL "https://raw.githubusercontent.com/radius-project/radius/main/deploy/install.sh" | /bin/bash`. This curl is taken from [here](https://docs.radapp.io/getting-started/#2-install-radius-cli).

### Observed behavior (required)
```
> curl -fsSL "https://raw.githubusercontent.com/radius-project/radius/main/deploy/install.sh" | /bin/bash
Getting the latest Radius CLI...
Your system is darwin_arm64
Installing Radius CLI...

Installing v0.26.8 Radius CLI...
Downloading https://github.com/radius-project/radius/releases/download/v0.26.8/rad_darwin_arm64...
Password:
rad installed into /usr/local/bin successfully
Installing rad-bicep ("rad bicep download")...
Downloading Bicep for channel 0.26...
Attempt 1 failed to download bicep: failed to resolve 0.26: GET "https://ghcr.io/v2/radius-project/radius/bicep/rad-bicep/macos-arm64/manifests/0.26": GET "https://ghcr.io/token?scope=repository%3Aradius-project%2Fradius%2Fbicep%2Frad-bicep%2Fmacos-arm64%3Apull&service=ghcr.io": response status code 403: denied: denied
Retrying...Attempt 2 failed to download bicep: failed to resolve 0.26: GET "https://ghcr.io/v2/radius-project/radius/bicep/rad-bicep/macos-arm64/manifests/0.26": GET "https://ghcr.io/token?scope=repository%3Aradius-project%2Fradius%2Fbicep%2Frad-bicep%2Fmacos-arm64%3Apull&service=ghcr.io": response status code 403: denied: denied
Retrying...Attempt 3 failed to download bicep: failed to resolve 0.26: GET "https://ghcr.io/v2/radius-project/radius/bicep/rad-bicep/macos-arm64/manifests/0.26": GET "https://ghcr.io/token?scope=repository%3Aradius-project%2Fradius%2Fbicep%2Frad-bicep%2Fmacos-arm64%3Apull&service=ghcr.io": response status code 403: denied: denied
Retrying...Attempt 4 failed to download bicep: failed to resolve 0.26: GET "https://ghcr.io/v2/radius-project/radius/bicep/rad-bicep/macos-arm64/manifests/0.26": GET "https://ghcr.io/token?scope=repository%3Aradius-project%2Fradius%2Fbicep%2Frad-bicep%2Fmacos-arm64%3Apull&service=ghcr.io": response status code 403: denied: denied
Retrying...Attempt 5 failed to download bicep: failed to resolve 0.26: GET "https://ghcr.io/v2/radius-project/radius/bicep/rad-bicep/macos-arm64/manifests/0.26": GET "https://ghcr.io/token?scope=repository%3Aradius-project%2Fradius%2Fbicep%2Frad-bicep%2Fmacos-arm64%3Apull&service=ghcr.io": response status code 403: denied: denied
Retrying...Attempt 6 failed to download bicep: failed to resolve 0.26: GET "https://ghcr.io/v2/radius-project/radius/bicep/rad-bicep/macos-arm64/manifests/0.26": GET "https://ghcr.io/token?scope=repository%3Aradius-project%2Fradius%2Fbicep%2Frad-bicep%2Fmacos-arm64%3Apull&service=ghcr.io": response status code 403: denied: denied
Retrying...Attempt 7 failed to download bicep: failed to resolve 0.26: GET "https://ghcr.io/v2/radius-project/radius/bicep/rad-bicep/macos-arm64/manifests/0.26": GET "https://ghcr.io/token?scope=repository%3Aradius-project%2Fradius%2Fbicep%2Frad-bicep%2Fmacos-arm64%3Apull&service=ghcr.io": response status code 403: denied: denied
Retrying...Attempt 8 failed to download bicep: failed to resolve 0.26: GET "https://ghcr.io/v2/radius-project/radius/bicep/rad-bicep/macos-arm64/manifests/0.26": GET "https://ghcr.io/token?scope=repository%3Aradius-project%2Fradius%2Fbicep%2Frad-bicep%2Fmacos-arm64%3Apull&service=ghcr.io": response status code 403: denied: denied
Retrying...Attempt 9 failed to download bicep: failed to resolve 0.26: GET "https://ghcr.io/v2/radius-project/radius/bicep/rad-bicep/macos-arm64/manifests/0.26": GET "https://ghcr.io/token?scope=repository%3Aradius-project%2Fradius%2Fbicep%2Frad-bicep%2Fmacos-arm64%3Apull&service=ghcr.io": response status code 403: denied: denied
Retrying...Error: failed to download bicep: failed to resolve 0.26: GET "https://ghcr.io/v2/radius-project/radius/bicep/rad-bicep/macos-arm64/manifests/0.26": GET "https://ghcr.io/token?scope=repository%3Aradius-project%2Fradius%2Fbicep%2Frad-bicep%2Fmacos-arm64%3Apull&service=ghcr.io": response status code 403: denied: denied

TraceId:  5dd55f8debd087179dbf8da34ab3ea85

Failed to install rad-bicep
Failed to install Radius CLI
For support, go to https://github.com/radius-project/radius
```

### Desired behavior (required)
Install rad

### rad Version (required)
NA

### Operating system (required)
MacOS Ventura 13.6 (M2)

## Additional context
It is strange to get a 403.

[AB#9965](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/9965)

### PR DESCRIPTION
**Pull request by vinayada1**
# Description

Fixes issue below in #6597 
curl -fsSL "https://raw.githubusercontent.com/radius-project/radius/main/deploy/install.sh" | /bin/bash
Getting the latest Radius CLI...
Your system is darwin_arm64
/bin/bash: line 91: /usr/local/bin/rad: Permission denied

Radius CLI is detected. Current version:
Reinstalling Radius CLI - /usr/local/bin/rad...

Installing v0.26.8 Radius CLI...
Downloading https://github.com/radius-project/radius/releases/download/v0.26.8/rad_darwin_arm64...
Password:
rad installed into /usr/local/bin successfully
Installing rad-bicep ("rad bicep download")...
/bin/bash: line 179: /usr/local/bin/rad: Permission denied
Failed to install rad-bicep
Failed to install Radius CLI
For support, go to https://github.com/radius-project/radius

## Type of change

- This pull request fixes a bug in Radius and has an approved issue (issue link required).

Fixes: #6597 

### Summary
🛠️🔐🚀

Fix permission issue with radius CLI installation. Make `deploy/install.sh` script more robust by allowing any user to execute the temporary `radius` binary.

> _`chmod` for all users_
> _Fixes permission issue_
> _Winter of discontent_

### Walkthrough
*  Make the radius CLI executable by all users after installation ([link](https://github.com/radius-project/radius/pull/6618/files?diff=unified&w=0#diff-ed1191c237ea4ba8f2011568f4ed0208c8d0ca36cbde1285828a61b4ff2128b4L170-R170))

### CODE REVIEW

**Comment by rynowak** [comment]
Did we figure out the repro & root cause for this? eg: why are some users successful and others are failing.

**Comment by vinayada1** [comment]
> Did we figure out the repro & root cause for this? eg: why are some users successful and others are failing.

No, I am working on that part. However, we can make this fix for now so that more users are not affected. I will add my findings here.

**Review by sk593 — APPROVED** [review]

**Comment by vinayada1** [comment]
> > Did we figure out the repro & root cause for this? eg: why are some users successful and others are failing.
> 
> No, I am working on that part. However, we can make this fix for now so that more users are not affected. I will add my findings here.

This looks like the problem:-
On the machine with the repro, the file permissions show up as:-
-rw-r--r-x  1 root  admin  67688368 Nov  1 10:21 /usr/local/bin/rad
 
and account membership shows the user is a part of admin group:-
~/radius/radius % id -Gn <username>
staff everyone localaccounts _appserverusr admin _appserveradm _lpadmin _appstore _lpoperator _developer _analyticsusers com.apple.access_ftp com.apple.access_screensharing com.apple.access_ssh com.apple.access_remote_ae com.apple.sharepoint.group.1
 
Therefore, the group permissions apply in this case which is "cannot execute"
 
On a machine with no repro, this shows up as:-
-rw-r--r-x  1 root  wheel  67688368 Nov  1 10:21 /usr/local/bin/rad
 
Here too, account membership shows up the same as before, which means the account is NOT a part of wheel group. As a result "others" permissions apply in this case which is "can execute"
 
We tried changing the user group for the file on the machine with no repro to "admin" using chgrp command and we see the permission denied error

**Review by AaronCrawfis — APPROVED** [review]

**Pull request merged**
