### PR TITLE
refactoring helm chart 

### PR DESCRIPTION
**Pull request by nithyatsu**
# Description
rad install --set command can now be used to set helm values.
This PR is to refactor helm values.yaml structure and provide final documentation for different values that can be set using rad install set.

## Issue reference

Fixes: #5343 

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Adds necessary unit tests for change
* [ ] Adds necessary E2E tests for change
* [ ] Unit tests passing
* [ ] Extended the documentation / Created issue for it

### CODE REVIEW

**Review by youngbupark — APPROVED** [review]
I left minor comments. Please address them before merging :) Also please validate the values in helm chart too.

**Review by ytimocin — APPROVED** [review]
LGTM other than a few nits

**Review by vinayada1 — APPROVED** [review]
added a nit

**Review by kachawla — APPROVED** [review]

**Review by kachawla — COMMENTED** [review]
Should this client be updated as well to expect updated keys? https://github.com/project-radius/radius/blob/main/pkg/cli/helm/radiusclient.go#L245

**Pull request merged**
