### PR TITLE
Temporarily skipping AWS S3 functional tests

### LINKED ISSUE #6524: Scheduled functional test failed - Run ID: 6581917730
## Bug information 

This bug is generated automatically if the scheduled functional test fails. The Radius functional test operates on a schedule of every 4 hours during weekdays and every 12 hours over the weekend. It's important to understand that the test may fail due to workflow infrastructure issues, like network problems, rather than the flakiness of the test itself. For the further investigation, please visit [here](https://github.com/radius-project/radius/actions/runs/6581917730).

[AB#9872](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/9872)

### LINKED ISSUE #6527: Scheduled functional test failed - Run ID: 6583407448
## Bug information 

This bug is generated automatically if the scheduled functional test fails. The Radius functional test operates on a schedule of every 4 hours during weekdays and every 12 hours over the weekend. It's important to understand that the test may fail due to workflow infrastructure issues, like network problems, rather than the flakiness of the test itself. For the further investigation, please visit [here](https://github.com/radius-project/radius/actions/runs/6583407448).

[AB#9873](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/9873)

### LINKED ISSUE #6530: Scheduled functional test failed - Run ID: 6585335663
## Bug information 

This bug is generated automatically if the scheduled functional test fails. The Radius functional test operates on a schedule of every 4 hours during weekdays and every 12 hours over the weekend. It's important to understand that the test may fail due to workflow infrastructure issues, like network problems, rather than the flakiness of the test itself. For the further investigation, please visit [here](https://github.com/radius-project/radius/actions/runs/6585335663).

[AB#9875](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/9875)

### LINKED ISSUE #6531: Scheduled functional test failed - Run ID: 6587819042
## Bug information 

This bug is generated automatically if the scheduled functional test fails. The Radius functional test operates on a schedule of every 4 hours during weekdays and every 12 hours over the weekend. It's important to understand that the test may fail due to workflow infrastructure issues, like network problems, rather than the flakiness of the test itself. For the further investigation, please visit [here](https://github.com/radius-project/radius/actions/runs/6587819042).

[AB#9876](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/9876)

### LINKED ISSUE #6534: Scheduled functional test failed - Run ID: 6590352800
## Bug information 

This bug is generated automatically if the scheduled functional test fails. The Radius functional test operates on a schedule of every 4 hours during weekdays and every 12 hours over the weekend. It's important to understand that the test may fail due to workflow infrastructure issues, like network problems, rather than the flakiness of the test itself. For the further investigation, please visit [here](https://github.com/radius-project/radius/actions/runs/6590352800).

[AB#9878](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/9878)

### PR DESCRIPTION
**Pull request by willdavsmith**
# Description

It seems like AWS CloudControl has made changes to the resource type schema. The `BucketName` used to be the primaryIdentifier, but it seems to have been replaced with `Id` which is a read-only property. This makes `S3` a non-idempotent resource and we can't deploy it reliably with Radius. This is outside of our control. For now, we should disable these tests while we figure out a solution/replacement.

Related issue: https://github.com/radius-project/radius/issues/6535

## Type of change

- This pull request is a minor refactor, code cleanup, test improvement, or other maintenance task and doesn't change the functionality of Radius (issue link optional).

Fixes: https://github.com/radius-project/radius/issues/6524
Fixes: https://github.com/radius-project/radius/issues/6527
Fixes: https://github.com/radius-project/radius/issues/6530
Fixes: https://github.com/radius-project/radius/issues/6531
Fixes: https://github.com/radius-project/radius/issues/6534

### Summary
:bug::wrench::mute:

Skip two AWS-related tests in the `test/functional/shared` directory that fail due to an AWS credentials issue. This is a temporary workaround until the issue is fixed.

> _`Test_AWS_*` skipped_
> _Credentials bug blocks them_
> _Winter of waiting_

### Walkthrough
* Skip the `Test_AWS_Mechanics` function in the `mechanics_test` package to avoid failing due to an AWS credentials issue ([link](https://github.com/radius-project/radius/pull/6536/files?diff=unified&w=0#diff-531a6f46ae9d530508fc569f3d8efb677f5c2b85ef21732415c71fd370f62050R31))
* Skip the `Test_AWS_S3Bucket` function in the `resource_test` package for the same reason, both in the `TestMain` and the `Test_AWS_S3Bucket` functions ([link](https://github.com/radius-project/radius/pull/6536/files?diff=unified&w=0#diff-fbc42064371b122a7ca2d92bfbd5452a51f680c7face11e8db22a71cd7d58e5bR29), [link](https://github.com/radius-project/radius/pull/6536/files?diff=unified&w=0#diff-fbc42064371b122a7ca2d92bfbd5452a51f680c7face11e8db22a71cd7d58e5bR68))

### CODE REVIEW

**Review by lakshmimsft — DISMISSED** [review]

**Comment by lakshmimsft** [comment]
@willdavsmith, is this test working? https://github.com/radius-project/radius/blob/3362c5beb78c78f13080240610551bb5bdee5f1f/test/functional/shared/resources/extender_test.go#L100

**Comment by willdavsmith** [comment]
> @willdavsmith, is this test working?
> 
> https://github.com/radius-project/radius/blob/3362c5beb78c78f13080240610551bb5bdee5f1f/test/functional/shared/resources/extender_test.go#L100

I think I missed this! Thanks. will update

**Review by lakshmimsft — APPROVED** [review]

**Review by ytimocin — APPROVED** [review]

**Comment by lakshmimsft** [comment]
merging to stop functional test failures.

**Pull request merged**
