### PR TITLE
docs: fix typos

### PR DESCRIPTION
**Pull request by daixiang0**
# Description

Fix typos.

### CODE REVIEW

**Review by AaronCrawfis — DISMISSED** [review]

**Comment by daixiang0** [comment]
@AaronCrawfis seems CI need extra approval.

**Comment by AaronCrawfis** [comment]
> @AaronCrawfis seems CI need extra approval.

Just kicked off the CI. We're actually addressing some permission updates as we move to a fork-based contribution model so you may see some failures. Working to address that ASAP

**Comment by rynowak** [comment]
Thanks @daixiang0 for submitting this. We're having some issues with the PR checks from a fork that haven't been resolved yet. I'm going to go ahead and merge this PR since it's a docs-only change and won't break anything.

**Review by rynowak — COMMENTED** [review]
:shipit: Thanks!

**Pull request merged**
