### PR TITLE
Documentation for a new sample app for reference to the local platform development

### PR DESCRIPTION
**Pull request by jasonviviano**
# Description

Documentation for  a tutorial based on local development for radius.

## Issue reference

https://github.com/project-radius/radius/issues/1735

### CODE REVIEW

**Review by AaronCrawfis — CHANGES_REQUESTED** [review]
This is a really great sample for the container apps reference application! Well done on getting this started!! Super excited to have this for 0.9

However, this isn't local development documentation. We'll need to add a page at https://edge.radapp.dev/platforms/local/ which covers what the local environment is, how it works (at a high level), and how to create/delete/run/etc.

I recommend renaming/updating this PR to add the new container apps sample, and separately make another PR that adds local environment docs.

**Review by rynowak — COMMENTED** [review]
Also looking for some coverage on `rad.yaml` and related files here. Good start.

**Review by emily-potyraj — CHANGES_REQUESTED** [review]
Great start! This example app is going to be a really nice addition to our docs. 

(btw, sorry to mark the PR as a draft earlier. clicked the wrong button.)

**Review by AaronCrawfis — CHANGES_REQUESTED** [review]
Getting super close! Added some notes on local dev docs

**Review by AaronCrawfis — CHANGES_REQUESTED** [review]
Updated the docs with my changes. Still have some open questions and issues

**Review by AaronCrawfis — APPROVED** [review]
Make sure to upload a new version of the .zip file to the bloc storage. The current one has a typo on the statestore br

**Pull request merged**
