### PR TITLE
Adding names to the etag unit tests

### LINKED ISSUE #6887: Some ETag unit tests missing names
## Overview of feature request
Some ETag unit tests are missing names which is causing this comment on PRs: https://github.com/radius-project/radius/pull/6885#issuecomment-1834260957.

## Acceptance criteria
Names should be added to those unit tests.

## Additional context
https://github.com/radius-project/radius/pull/6885#issuecomment-1834260957

[AB#10598](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/10598)

### PR DESCRIPTION
**Pull request by ytimocin**
# Description
Adding names to the etag unit tests.

## Type of change
- This pull request is a minor refactor, code cleanup, test improvement, or other maintenance task and doesn't change the functionality of Radius (issue link optional).

Fixes: #6887 

### Summary
🧪🎨📝

Refactor test cases for `TestValidateEtag_IfMatch` in `util_test.go` to use names and readable format. This improves the test code quality and style for the armrpc package.

> _`armrpc` tests grow_
> _Refactored with names and style_
> _Autumn of cleanup_

### Walkthrough
*  Refactor test cases for `TestValidateEtag_IfMatch` function to include name field and use consistent format ([link](https://github.com/radius-project/radius/pull/6886/files?diff=unified&w=0#diff-8f964ad7752e403193ac37a0a9f39543c5003c0a7c04f4d4521b5e40808aecf9L73-R117))

### CODE REVIEW

**Review by kachawla — COMMENTED** [review]
Thanks for improving this. Should this test be updated as well https://github.com/radius-project/radius/blob/de6e319fe99192059bcbc4a730a71e28d6bc92eb/pkg/armrpc/frontend/controller/util_test.go#L135?

**Review by kachawla — APPROVED** [review]

**Review by rynowak — COMMENTED** [review]
:shipit: thanks for fixing this!

**Pull request merged**
