### PR TITLE
generic swagger and its generated client for Applications.Core

### PR DESCRIPTION
**Pull request by nithyatsu**
# Description

We introduce {scope} in swagger to represent /subscriptions/{subscriptionID}/resourceGroup/{resourceGroupID} for azure hosted radius, /resourceGroup/{resourceGroupID} for k8s env hosted radius.

## Issue reference

Please reference the issue this PR will close: #_2331_

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [X] Code compiles correctly
* [ ] Adds necessary unit tests for change
* [ ] Adds necessary E2E tests for change
* [ ] Unit tests passing
* [ ] Extended the documentation / Created issue for it

### CODE REVIEW

**Review by kachawla — COMMENTED** [review]
Could you please include changes to connector RP specs as well? 
https://github.com/project-radius/radius/tree/main/swagger/specification/applications/resource-manager/Applications.Connector/preview/2022-03-15-privatepreview

**Review by shalabhms — CHANGES_REQUESTED** [review]
Please change the current Swagger files only.

**Review by asilverman — APPROVED** [review]
LGTM

**Review by bjoginapally — APPROVED** [review]

**Review by shalabhms — APPROVED** [review]
Thanks for resolving comments. /lgtm.

**Review by jkotalik — APPROVED** [review]

**Pull request merged**
