### PR TITLE
Adding in a cli command to show recipe details (including parameters)

### PR DESCRIPTION
**Pull request by snehabandla**
# Description

-Add in a cli command to show recipe details. This is to allow users to see supported parameters and their details.
Command is invoked as follows:
`$ rad recipe show --name <recipe-name>`

An example:
```
$ rad recipe show --name prod
```
image

-Refactoring check to see if recipe exists to a common util.

## Issue reference

Fixes: https://dev.azure.com/azure-octo/Incubations/_workitems/edit/5290

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Adds necessary unit tests for change
* [ ] Adds necessary E2E tests for change
* [x] Unit tests passing
* [ ] Extended the documentation / Created issue for it

### CODE REVIEW

**Review by AaronCrawfis — CHANGES_REQUESTED** [review]
Added some notes on descriptions and examples

**Review by bjoginapally — CHANGES_REQUESTED** [review]
Looks like the operation to show recipe isn't implemented

**Review by AaronCrawfis — APPROVED** [review]
Descriptions look good to me. Thanks!

**Review by bjoginapally — APPROVED** [review]
Approving to unblock subsequent PRs to refactor recipe related operations and implementation.

**Review by kachawla — APPROVED** [review]
Let's check on flag / positional arg and follow up in this or separate pr if needed.

**Review by shalabhms — APPROVED** [review]

**Review by kachawla — COMMENTED** [review]
Can you update description with an example of what the output of the command looks like?

**Pull request merged**
