### PR TITLE
`rad bicep publish` command

### PR DESCRIPTION
**Pull request by ytimocin**
# Description
`rad bicep publish` command.

Usage:
1. `rad bicep publish --file /recipes/redis.recipe.bicep --target br:ytimocin.azurecr.io/recipes/redis-recipe:v1`
2. `rad bicep publish --file /recipes/redis.recipe.bicep --target br:index.docker.io/ytimocin/redis-recipe:v1`

Screenshots:

image

image

## Issue reference
Fixes: radius-project/core-team#1138 

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Adds necessary unit tests for change
* [x] Adds necessary E2E tests for change
* [x] Unit tests passing
* [x] Extended the documentation / Created issue for it

### CODE REVIEW

**Review by shalabhms — CHANGES_REQUESTED** [review]
Please change the term in the command  to "file" from "module". Thanks.

**Review by rynowak — CHANGES_REQUESTED** [review]
Looks like we're still missing handling for `br:`.

**Review by shalabhms — APPROVED** [review]
Thanks for resolving comments. /lgtm.

**Review by AaronCrawfis — APPROVED** [review]
Strings all look good

**Review by rynowak — APPROVED** [review]

**Pull request merged**
