### PR TITLE
Add `ok-to-test` trigger for functional tests

### LINKED ISSUE #5632: Remove automatic e2e test trigger
radius-project/core-team#539 adds /ok-to-test comment to trigger to functional tests on radius. Right after we open source, we should remove the "on pull_request" trigger to start these tests. It would be better to leave this in for now till we open source

[AB#8078](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/8078)

### PR DESCRIPTION
**Pull request by willdavsmith**
# Description

* Re-adding `ok-to-test` to trigger functional tests

## Type of change

- This pull request is a minor refactor, code cleanup, test improvement, or other maintenance task and doesn't change the functionality of Radius (issue link optional).

Fixes: #5632

### Summary
:no_entry_sign::clock1::point_right:

Remove `pull_request` trigger and add `ok-to-test` event for functional tests. This allows maintainers to manually run the tests on a pull request by sending a `repository_dispatch` event with the pull request number.

> _`pull_request` gone_
> _functional tests run on demand_
> _`ok-to-test` cuts_

### Walkthrough
* Remove `pull_request` trigger and add `ok-to-test` event type for `repository_dispatch` trigger in functional test workflow ([link](https://github.com/radius-project/radius/pull/6481/files?diff=unified&w=0#diff-c79f364a9293abaaa8595776b74674e24bec6287834e63ab8aa7aec6a42f0dbcL24-R26)). This allows maintainers to manually run the functional tests on a pull request by sending a `repository_dispatch` event with the `ok-to-test` type and the pull request number as the payload. The workflow file is `.github/workflows/functional-test.yaml`.

### CODE REVIEW

**Review by AaronCrawfis — DISMISSED** [review]

**Review by kachawla — DISMISSED** [review]

**Comment by vinayada1** [comment]
What is this change needed for? I added the ok-to-test comment to your PR which triggered https://github.com/radius-project/radius/actions/runs/6550667187.

**Review by rynowak — APPROVED** [review]

**Pull request merged**
