### PR TITLE
Enable skipped bubble tea tests by updating the related libraries

### LINKED ISSUE #5762: Re-enable skipped bubbletea tests
We had to disable some of our UI tests due to problems with the test framework provided by Bubbletea.

This item tracks re-enabling the tests. Search for the issue number to find them 👍 

[AB#8381](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/8381)

### PR DESCRIPTION
**Pull request by ytimocin**
# Description
1. Update necessary libraries.
2. Reenable skipped bubble tea tests.

## Type of change
- This pull request is a minor refactor, code cleanup, test improvement, or other maintenance task and doesn't change the functionality of Radius (issue link optional).
Fixes: #5762 

### Summary
🐛🚀🧪

Updated `go.mod` file and several test files to use newer package versions and fix test failures. Removed unnecessary `t.Skip` calls and comments from `display_test.go` and `text_test.go`.

> _Some tests were skipped in the past_
> _But now they can run very fast_
> _The `teatest` package_
> _Fixed the framework's baggage_
> _And `go.mod` got a new cast_

### Walkthrough
*  Update `teatest` package to fix bugs and improve test coverage ([link](https://github.com/radius-project/radius/pull/6823/files?diff=unified&w=0#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6L28-R28))
  * Remove `t.Skip` calls and comments from `Test_summaryModel` in `display_test.go` and `Test_NewTextModel_UpdateEchoMode` in `text_test.go` ([link](https://github.com/radius-project/radius/pull/6823/files?diff=unified&w=0#diff-652ce55ed8af3f822e7c546447ced1d2daf2e8d2c586f783cdac0ec3f9bd8513L37-R37), [link](https://github.com/radius-project/radius/pull/6823/files?diff=unified&w=0#diff-a95b3c117c873821d9473cd582ee12f2ffccb36c71d5fd41b1a3897f0268d957L75-L81))
* Update `go-isatty`, `golang.org/x/sync`, `golang.org/x/text`, `golang.org/x/sys`, and `golang.org/x/term` packages to ensure compatibility with latest Go and dependencies ([link](https://github.com/radius-project/radius/pull/6823/files?diff=unified&w=0#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6L51-R51), [link](https://github.com/radius-project/radius/pull/6823/files?diff=unified&w=0#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6L80-R81), [link](https://github.com/radius-project/radius/pull/6823/files?diff=unified&w=0#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6L274-R276))
* Add `github.com/stretchr/objx` package as an indirect dependency ([link](https://github.com/radius-project/radius/pull/6823/files?diff=unified&w=0#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6R97))

### CODE REVIEW

**Review by kachawla — APPROVED** [review]
Thanks for updating these tests!

**Comment by rynowak** [comment]
@ytimocin - did you try this out locally? Before the upgrade you said it was easy to reproduce the failures. Is that better?

**Comment by ytimocin** [comment]
> @ytimocin - did you try this out locally? Before the upgrade you said it was easy to reproduce the failures. Is that better?

Yes, after I upgraded the libraries I haven't run into failures and I have tried a good amount.

**Pull request merged**
