### PR TITLE
Enable local environments to deploy azure resources

### PR DESCRIPTION
**Pull request by asilverman**
# Description

Enables the user to set the SPN that will be used by the Deployment Engine to make ARM requests

## Issue reference

Please reference the issue this PR will close: project-radius/deployment-engine#56

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Adds necessary unit tests for change
* [] Adds necessary E2E tests for change - no e2e available
* [x] Unit tests passing
* [x] Extended the documentation / Created issue for it

### CODE REVIEW

**Review by AaronCrawfis — DISMISSED** [review]
1. Prompt for subscription and resource group after the user opts-in to adding an  Azure provider, instead of before
2. Print instructions for creating the service principal before prompting for the app Id, so that wat the cursor lands on where they need to enter the appID
3. Remove /en-us/ from the docs link. Also check the Azure docs to see if there is an aka.ms shortlink for creating a service principal

**Review by jkotalik — APPROVED** [review]
Some minor feedback, LGTM otherwise.

**Review by AaronCrawfis — DISMISSED** [review]
Added comments on RBAC setup

**Review by AaronCrawfis — DISMISSED** [review]
Looking good! One suggestion and and a question

**Review by AaronCrawfis — APPROVED** [review]
Perfect! Thanks so much for making this a great flow!! Also love the colorized command output

:shipit:

**Review by AaronCrawfis — DISMISSED** [review]
Getting an error when deploying the following error:

```bicep
resource storageAccount 'Microsoft.Storage/storageAccounts@2021-06-01' = {
  name: 'aacrawfidevtest0606'
  location: 'westus3'
  sku: {
    name: 'Standard_LRS'
  }
  kind: 'StorageV2'
}
```

```bicep
PS D:\Repos\ProjectRadius\radius\cmd\rad> go run .\main.go deploy D:\scratch\app.bicep    
Building D:\scratch\app.bicep...
Deploying Application into environment 'dev'...

Deployment In Progress...

Error: Code="DeploymentFailed" Message="" Details=[{"additionalInfo":null,"code":"InternalServerError","details":null,"message":"{\n  \"error\": {\n    \"code\": \"ResourceDeploymentFailure\",\n    \"message\": \"Encountered internal server error. Diagnostic information: timestamp '06/06/2022 21:00:06', subscription id '\u003cnull\u003e', tracking id 'e4895b90-6f4c-436a-a5a4-517b2d433b0e', request correlation id '\u003cnull\u003e'.\"\n  }\n}","target":null}]
exit status 1
```

**Review by AaronCrawfis — APPROVED** [review]
Tested and working!

**Pull request merged**
