### PR TITLE
Fix long-running azure workflow syntax and re-enable for pull requests

### LINKED ISSUE #6497: Re-enable long-running Azure tests if the workflow file is changed in PR
## Overview of feature request

https://github.com/radius-project/radius/pull/6478 disables the long-running azure tests on PR. We should re-enable this for PRs that change this workflow.

## Acceptance criteria

* https://github.com/radius-project/radius/blob/main/.github/workflows/long-running-azure.yaml runs on PR if the file is changed.

### PR DESCRIPTION
**Pull request by shubham1172**
# Description

This PR fixes the YAML syntax error in https://github.com/radius-project/radius/actions/workflows/long-running-azure.yaml and re-enables running the workflow on pull requests whenever the workflow file is itself edited.

## Type of change

- This pull request is a minor refactor, code cleanup, test improvement, or other maintenance task and doesn't change the functionality of Radius (issue link optional).

Fixes: #6497

### Summary
🚀🧪🔒

Enable pull request trigger for long-running Azure workflow. This allows testing the `.github/workflows/long-running-azure.yaml` file changes before merging.

> _`pull_request` runs_
> _workflow on branch changes_
> _autumn leaves falling_

### Walkthrough
*  Enable workflow to run on pull requests that modify it ([link](https://github.com/radius-project/radius/pull/6547/files?diff=unified&w=0#diff-85cd86e7ae6da973e4808fe57f4fea7892ab78a499ba5aec72c0b3751a2cc226L44-R46))

### CODE REVIEW

**Comment by rynowak** [comment]
@willdavsmith can you help review this?

**Review by willdavsmith — APPROVED** [review]

**Comment by willdavsmith** [comment]
thanks for the contribution(s) @shubham1172 :) it looks like we need to move the long-running Azure test workflow to our functional workflow (ok-to-test enabled). For now I think we can merge this as-is with the understanding that it will fail if we try to update this workflow for now.

**Comment by rynowak** [comment]
@shalabhms - can you help merge this? The Azure functional test workflow will fail since this PR is from a fork. This is expected and should be bypassed.

@willdavsmith - can you create an issue to track the improvements we need for this workflow?

**Comment by shalabhms** [comment]
Thanks @shubham1172 for your contribution!

**Comment by willdavsmith** [comment]
https://github.com/radius-project/radius/issues/6555

**Pull request merged**
